### PR TITLE
Skip extras in precise ASTs (for now)

### LINKED ISSUE #204: Comments are mistakenly being unmarshalled into extraChildren fields
We don’t currently have support for extras like comments (cf #99), but in grammars that have named comment rules, the comments get added into the extra children field, which is causing Python modules to fail to unmarshal since `Either CompoundStatement SimpleStatement` can’t represent `Comment`.

### PR DESCRIPTION
**Pull request by robrix**
This PR fixes a bug where named nodes occurring within extras were being added to the extra children field, which was definitely a bug altho as @maxbrunsfeld notes is kinda confusing in terms of nomenclature.

Since we haven’t yet got a fix for #99, we just drop them for now.

Fixes #204.

### CODE REVIEW

File: tree-sitter-python/test/Main.hs [hunk 1]
```diff
@@ -31,6 +31,7 @@ function = Py.ExpressionStatementSimpleStatement (Py.ExpressionStatement () [Lef
 prop_simpleExamples :: Property
 prop_simpleExamples = property $ do
   "" `shouldParseInto` Py.Module { Py.ann = (), Py.extraChildren = [] }
+  "# bah" `shouldParseInto` Py.Module { Py.ann = (), Py.extraChildren = [] }
```
Comment (robrix) [inline tree-sitter-python/test/Main.hs]: This test fails on `master`.

File: tree-sitter/src/TreeSitter/Node.hs [hunk 2]
```diff
@@ -24,6 +24,7 @@ data Node = Node
   , nodeEndByte    :: !Word32
   , nodeChildCount :: !Word32
   , nodeIsNamed    :: !CBool
+  , nodeIsExtra    :: !CBool
```
Comment (robrix) [inline tree-sitter/src/TreeSitter/Node.hs]: Thank you @maxbrunsfeld! 💖

File: tree-sitter/src/TreeSitter/Unmarshal.hs [hunk 3]
```diff
@@ -221,7 +221,8 @@ getFields = go Map.empty -- >>= \fields -> liftIO (print (Map.keys fields)) >> p
               keepGoing <- step
               let fs' = case fieldName of
                     Just fieldName' -> Map.insertWith (flip (++)) fieldName' [node'] fs
-                    _ -> if nodeIsNamed node' /= 0
+                    -- NB: We currently skip “extra” nodes (i.e. ones occurring in the @extras@ rule), pending a fix to https://github.com/tree-sitter/haskell-tree-sitter/issues/99
+                    _ -> if nodeIsNamed node' /= 0 && nodeIsExtra node' == 0
                       then Map.insertWith (flip (++)) (FieldName "extraChildren") [node'] fs
                       else fs
```
Comment (robrix) [inline tree-sitter/src/TreeSitter/Unmarshal.hs]: The addition of the `nodeIsExtra` test means that we just silently drop such fields. It won’t be a big change to nest the conditionals and add extras into a dedicated `extras` field instead, once we’re fixing #99. @maxbrunsfeld made the (v. good) point that having both `extras` and `extraChildren` fields is gonna be super confusing, so maybe we should also rename the latter to `otherChildren` at that point.

File: tree-sitter/test/Spec.hs [hunk 4]
```diff
@@ -30,8 +30,8 @@ prop_Node_sizeOf = property $
   sizeOf (undefined :: Node) === fromIntegral sizeof_node
 
 prop_Node_roundtrips = property $ do
-  peeked <- liftIO (with (Node (TSNode 1 2 3 4 nullPtr nullPtr) nullPtr 1 (TSPoint 2 3) (TSPoint 4 5) 6 7 8 9) peek)
-  peeked ===              Node (TSNode 1 2 3 4 nullPtr nullPtr) nullPtr 1 (TSPoint 2 3) (TSPoint 4 5) 6 7 8 9
+  peeked <- liftIO (with (Node (TSNode 1 2 3 4 nullPtr nullPtr) nullPtr 1 (TSPoint 2 3) (TSPoint 4 5) 6 7 8 9 10) peek)
+  peeked ===              Node (TSNode 1 2 3 4 nullPtr nullPtr) nullPtr 1 (TSPoint 2 3) (TSPoint 4 5) 6 7 8 9 10
```
Comment (robrix) [inline tree-sitter/test/Spec.hs]: look at all the fields I give

look at them, Anakin

File: tree-sitter-go/tree-sitter-go.cabal [hunk 5]
```diff
@@ -14,16 +14,16 @@ build-type:          Simple
...
                      , tree-sitter-go-internal
   default-language:    Haskell2010
 
 library tree-sitter-go-internal
   exposed-modules:     TreeSitter.Go.Internal
   hs-source-dirs:      internal
-  build-depends:       base                 >= 4.12 && < 5
-                     , tree-sitter >= 0.1 && < 0.3
+  build-depends:       base
+                     , tree-sitter
```
Comment (robrix) [inline tree-sitter-go/tree-sitter-go.cabal]: Internal libraries can’t be used outside of the package they’re defined in, and any constraints they impose are effectively unioned with the public library, so I’ve just deleted them all and allowed the public library components to constrain things instead.

File: tree-sitter-go/tree-sitter-go.cabal [hunk 6]
```diff
@@ -1,6 +1,6 @@
 cabal-version:       2.2
 name:                tree-sitter-go
-version:             0.1.0.0
+version:             0.2.0.0
```
Comment (robrix) [inline tree-sitter-go/tree-sitter-go.cabal]: This is a major bump because it requires a major bump, I guess?

File: CHANGELOG.md [hunk 7]
```diff
@@ -1,8 +1,12 @@
...
 ### 0.1.0
 
 * Support for tree-sitter-go
 
 ### 0.0.0.1
 * Support for tree-sitter-javascript
 * Support for tree-sitter-c
-* Preliminary support for tree-sitter-ruby
\ No newline at end of file
+* Preliminary support for tree-sitter-ruby
```
Comment (robrix) [inline CHANGELOG.md]: Trailing newline, apparently.
