### PR TITLE
Safely convert nodeSymbol to grammar values

### LINKED ISSUE #145: Exceptions mapping nodeSymbol to Grammar datatypes using Enum instance
I've seen that `Grammar` has `ParseError` constructor, but for Nix I get `ERROR`:

```
canonix: toEnum{Grammar}: tag (65535) is outside of enumeration's range (0,98)
CallStack (from HasCallStack):
  error, called at ./TreeSitter/Nix.hs:15:1 in tree-sitter-nix-0.1.0-AcUfetAdPzz7lGcBxdaPNc:TreeSitter.Nix
```

_Originally posted by @domenkozar in https://github.com/tree-sitter/haskell-tree-sitter/issues/114#issuecomment-504347760_

### PR DESCRIPTION
**Pull request by robrix**
This PR:

- Moves `Symbol`, `SymbolType`, `TSSymbol`, and `symbolToName` into a new `TreeSitter.Symbol` module.
- Types `TreeSitter.Node.nodeSymbol` as `TSSymbol`.
- Defines a new `fromTSSymbol` function for safely mapping `TSSymbol` values with `tree-sitter`’s symbol semantics into `Symbol` datatypes.
- Fixes #145.

### CODE REVIEW

File: src/TreeSitter/Language.hs [hunk 1]
```diff
@@ -1,54 +1,45 @@
...
-        promote Auxiliary = 'Auxiliary
-        renameDups done [] = reverse done
-        renameDups done ((ty, name):queue) = if elem name (snd <$> done)
-                                      then renameDups done ((ty, name ++ "'") : queue)
-                                      else renameDups ((ty, name) : done) queue
+  let mkMatch symbolType str = match (conP (Name (OccName str) (NameQ modName)) []) (normalB [e|symbolType|]) []
+  (:) <$> dataD (pure []) name [] Nothing (flip normalC [] . mkName . snd <$> namedSymbols) [ derivClause Nothing (map conT [ ''Bounded, ''Enum, ''Eq, ''Ix, ''Ord, ''Show ]) ]
+      <*> [d|
+    instance Symbol $(conT name) where
+      symbolType = $(lamCaseE (uncurry mkMatch <$> namedSymbols)) |]
```
Comment (robrix) [inline src/TreeSitter/Language.hs]: I also took the opportunity to refactor this pretty significantly.

File: src/TreeSitter/Language.hs [hunk 2]
```diff
@@ -1,54 +1,45 @@
...
+
+renameDups :: [(a, String)] -> [(a, String)]
+renameDups = go mempty
+  where go _    []                = []
+        go done ((ty, name):rest) = let name' = if name `Set.member` done then name ++ "'" else name in (ty, name') : go (Set.insert name' done) rest
```
Comment (robrix) [inline src/TreeSitter/Language.hs]: This is quite a bit more straightforward, and no longer requires the `reverse`. It should also be more efficient due to the `Set`-based lookup instead of the linear search.

File: src/TreeSitter/Language.hs [hunk 3]
```diff
@@ -1,54 +1,45 @@
...
-import Data.Word
-import Foreign.C.String
-import Foreign.Ptr
-import Language.Haskell.TH
-import Language.Haskell.TH.Syntax
-import System.Directory
-import System.FilePath.Posix
+module TreeSitter.Language
+( module TreeSitter.Language
+, module TreeSitter.Symbol
```
Comment (robrix) [inline src/TreeSitter/Language.hs]: I’m re-exporting `TreeSitter.Symbol` for backwards compatibility; didn’t want to break @aymannadeem’s in-flight work in #145.

File: src/TreeSitter/Language.hs [hunk 4]
```diff
@@ -1,54 +1,47 @@
...
-  where clause modName symbolType str = Clause [ ConP (Name (OccName str) (NameQ modName)) [] ] (NormalB (ConE (promote symbolType))) []
-        promote Regular = 'Regular
-        promote Anonymous = 'Anonymous
-        promote Auxiliary = 'Auxiliary
-        renameDups done [] = reverse done
-        renameDups done ((ty, name):queue) = if elem name (snd <$> done)
-                                      then renameDups done ((ty, name ++ "'") : queue)
-                                      else renameDups ((ty, name) : done) queue
+  let mkMatch symbolType str = match (conP (Name (OccName str) (NameQ modName)) []) (normalB [e|symbolType|]) []
+  (:) <$> dataD (pure []) name [] Nothing (flip normalC [] . mkName . snd <$> namedSymbols) [ derivClause Nothing (map conT [ ''Bounded, ''Enum, ''Eq, ''Ix, ''Ord, ''Show ]) ]
```
Comment (patrickt) [inline src/TreeSitter/Language.hs]: Can we pull out some of these constituent parts (within the `(:) <$> dataD… <*> [d| … `) part into let-clauses? There's a little too much going on here for me to keep track of it as it stands.

File: src/TreeSitter/Language.hs (hunk 1 above)
Comment (patrickt) [reply src/TreeSitter/Language.hs]: This is gorgeous.

File: src/TreeSitter/Language.hs [hunk 5]
```diff
@@ -1,54 +1,47 @@
...
+      <*> [d|
+    instance Symbol $(conT name) where
+      symbolType = $(lamCaseE (uncurry mkMatch <$> namedSymbols)) |]
+
+renameDups :: [(a, String)] -> [(a, String)]
```
Comment (patrickt) [inline src/TreeSitter/Language.hs]: Would this be nicer with `mapAccumL`?

Comment (robrix) [reply src/TreeSitter/Language.hs]: It really is! Also, achievement unlocked: first time actually using `mapAccumL` 😊
