### PR TITLE
Faster unmarshalling iteration

### LINKED ISSUE #220: Validate Unmarshaling sooner/from tree-sitter
`Unmarshal` lives in `tree-sitter`, but we don't really get to test it until we load `tree-sitter-python`. This can delay useful feedback. To make sure we see the errors closer to the module where they live, @robrix proposed hard-coding syntax types that emulate what our TH-generated types would look like, ie.:

```
data Stmt a
  = IfStmt (If a)
  | BlockStmt (Block a)
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)

data Expr a
  = LitExpr (Lit a)
  | PlusExpr (Plus a)
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)

data Lit a = Lit { ann :: a, text :: Text.Text }
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)
data Plus a = Plus { ann :: a, lhs :: Expr a, rhs :: Expr a }
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)

data Block a = Block { ann :: a, body :: [Stmt a] }
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)

data If a = If { ann :: a, condition :: Expr a, consequence :: Stmt a, alternative :: Stmt a }
  deriving (Eq, Ord, Show, Foldable, Functor, Traversable, Generic1)
```

This would allow us to test/validate the unmarshal code is working without having to load language-specific projects where the unmarshaling is actually happening right now.

### PR DESCRIPTION
**Pull request by robrix**
This PR defines some datatypes and derives `Unmarshal` instances for them so that we can get immediate feedback on whether we’re actually able to derive the behaviours we want for the kinds of datatypes we generate with TH.

**NB:** the thing being optimized here is our workflow when iterating on `Unmarshal`, rather than e.g. the runtime performance of unmarshalling.

- [x] Fixes #220.

### CODE REVIEW

File: tree-sitter/src/TreeSitter/Unmarshal/Examples.hs [hunk 1]
```diff
@@ -0,0 +1,55 @@
+{-# LANGUAGE DeriveAnyClass, DeriveGeneric, DuplicateRecordFields, TypeOperators #-}
+module TreeSitter.Unmarshal.Examples () where
```
Comment (robrix) [inline tree-sitter/src/TreeSitter/Unmarshal/Examples.hs]: Adding these examples to the library means that we get instantaneous feedback when changes to `Unmarshal` affect which instances we can derive.

File: tree-sitter/tree-sitter.cabal [hunk 2]
```diff
@@ -47,6 +47,7 @@ library
                      , TreeSitter.GenerateSyntax
                      , TreeSitter.Deserialize
                      , TreeSitter.Cursor
+  other-modules:       TreeSitter.Unmarshal.Examples
```
Comment (robrix) [inline tree-sitter/tree-sitter.cabal]: We don’t want to actually expose these example datatypes to downstream consumers, so we include them in `other-modules` instead of `exposed-modules`.

File: tree-sitter/src/TreeSitter/Unmarshal/Examples.hs [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+-- | An example of a sum-of-products datatype.
+data Expr a
+  = IfExpr (If a)
+  | BlockExpr (Block a)
+  | LitExpr (Lit a)
+  | BinExpr (Bin a)
+  deriving (Generic, Unmarshal)
+
+-- | Product with multiple fields.
+data If a = If { ann :: a, condition :: Expr a, consequence :: Expr a, alternative :: Maybe (Expr a) }
```
Comment (robrix) [inline tree-sitter/src/TreeSitter/Unmarshal/Examples.hs]: These datatypes are intended to be representative, but not exhaustive. We employ sums, products, leaves, and anonymous leaves; as well as `Maybe`, `[]`, and `:+:`; but not `NonEmpty`.

File: tree-sitter/src/TreeSitter/Unmarshal/Examples.hs [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+import qualified Data.Text as Text
+import GHC.Generics ((:+:), Generic)
+import TreeSitter.Unmarshal
+
+-- | An example of a sum-of-products datatype.
+data Expr a
+  = IfExpr (If a)
+  | BlockExpr (Block a)
+  | LitExpr (Lit a)
+  | BinExpr (Bin a)
```
Comment (robrix) [inline tree-sitter/src/TreeSitter/Unmarshal/Examples.hs]: (When we implement #210, we’ll want to come back and replace this with a type synonym instead.)
